import type { Metadata } from "next";
import { Inter, Public_Sans } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const publicSans = Public_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${publicSans.className} antialiased flex flex-col min-h-screen`}
      >
        <Toaster position="top-right" />
        <main className="grow">{children}</main>
      </body>
    </html>
  );
}
